version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/app"
    target-branch: "develop"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
